sudo: false
language: haxe

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/02e5112c59e387a9d167
      - https://webhooks.gitter.im/e/2cf2b3fce38bfb758c65
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

os:
  - linux

haxe:
  - "3.2.1"
  - development

before_install:
    - git clone https://github.com/haxeui/haxeui-core.git --depth=1
    - haxelib dev haxeui-core haxeui-core


install:
    - haxelib install hscript
    #- haxelib dev haxeui-html5 $TRAVIS_BUILD_DIR

script:
    - haxe build.hxml